apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-per-express
  labels:
    app: mongo-per-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-per-express
  template:
    metadata:
      labels:
        app: mongo-per-express
    spec:
      containers:
        - name: mongo-per-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-per-creds
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-per-creds
                  key: password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-per-config
                  key: mongo-per-url
